title: para sa kultura
logo: /assets/img/Flag_of_the_Philippines.svg.png
description: raelynn's repository :)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
